#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.9.0 */
/* https://trip5.github.io/yoradio-docs/docs/myoptions-generator.html?b=ESP32-DevKit-V1_38Pin&r=72,1,2,9,31,41,43&i=1,2,3,4,15,16,17&v=4,5,-1,255,27,26,25 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library */

/* !!! Do not be alarmed by some #defines missing. Default values are not included in this file. !!! */
/* !!! Values of 255 must be edited before using (except I2S_DOUT 255 which is used to disable I2S Sound). !!! */

#define L10N_LANGUAGE			EN
#define DSP_MODEL			DSP_ILI9488
#define BRIGHTNESS_PIN			255


#endif
